backend:
  name: github
  repo: krubenok/nerd-ramblings
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/assets
public_folder: assets
publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "decks"
    label: "Decks"
    folder: "content/decks"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
