# on:
# push
# schedule:
# is a special character in YAML so you have to quote this string
#   - cron: "* 6 * * SUN"

name: Pull Request on Branch Push
on: push
jobs:
  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: "master"
          PULL_REQUEST_FROM_BRANCH: "develop"
